package gnopm

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
)

// CIOptions controls what `gnopm tool ci` does beyond checking.
type CIOptions struct {
	// Comment posts the report as a single sticky pull request comment,
	// updating it in place on later runs.
	Comment bool
	// Base is the ref to compare against. Empty means detect it.
	Base string
	// RPC and ChainID skip chain discovery, as they do on bump and tidy: for
	// a local gnodev, and for the test that drives a fake chain.
	RPC, ChainID string
}

// CI is the whole of a repository's gnopm continuous integration.
//
// The point is that a workflow calling this should be about ten lines and
// still produce something worth reading. Everything a consuming repository
// would otherwise reimplement lives here instead, so the value travels with
// the binary rather than with whoever copied a workflow first.
//
// It writes a Markdown report to stdout, appends it to the GitHub Actions job
// summary when running in one, and exits non-zero when a check fails. The
// report is the same either way, so a local run tells you exactly what CI will
// say.
func CI(e *Env, opts CIOptions) error {
	lock, err := readLock(e.Root)
	if err != nil {
		return err
	}
	pkgs, err := scanPackages(e.Root)
	if err != nil {
		return err
	}
	pinned := materializedEntries(lock)
	base := upstreamRef(e.Root, opts.Base)

	type check struct {
		name, detail string
		ok           bool
		// warn is reported and does not fail the run. Reserved for the thing
		// that is worth saying out loud but that a repository may have a good
		// reason to do: turning those red teaches people to skip the check.
		warn bool
	}
	var checks []check
	add := func(name string, err error, okDetail string) {
		if err != nil {
			checks = append(checks, check{name, firstLine(err.Error()), false, false})
			return
		}
		checks = append(checks, check{name, okDetail, true, false})
	}
	skip := func(name, why string) {
		checks = append(checks, check{name, "skipped: " + why, true, false})
	}

	// Each check is reported separately rather than as one pass/fail, because
	// "something is wrong with your lock" is not an actionable sentence.
	add("the lock describes the working tree", consistent(lock, pkgs), "every package accounted for")
	add("pinned versions reproduce from history", reproduces(e.Root, pinned),
		fmt.Sprintf("%d version(s) rebuilt and hashed", len(pinned)))
	if base == "" {
		skip("pins survive a squash merge", "no upstream ref detected")
		skip(publishedEditCheck, "no upstream ref detected")
	} else {
		add("pins survive a squash merge", stranded(e.Root, pinned, base),
			"every pin is already on "+base)

		// The one check that needs a chain, and the one that warns instead of
		// failing. It runs last so a network round trip never delays a verdict
		// the repository could reach on its own.
		switch edited, err := editedInPlace(e.Root, pkgs, base); {
		case err != nil:
			skip(publishedEditCheck, firstLine(err.Error()))
		case len(edited) == 0:
			checks = append(checks, check{publishedEditCheck, "no package edited in place", true, false})
		default:
			probe, err := NewProbe(e, edited[0].Module, opts.RPC, opts.ChainID)
			if err != nil {
				// Offline, or the chain is down. The candidates are still worth
				// naming: an author reading this knows which ones to check.
				skip(publishedEditCheck, fmt.Sprintf("%d package(s) edited in place, chain unreachable: %s",
					len(edited), firstLine(err.Error())))
				break
			}
			hit, err := publishedEdits(edited, probe.Published)
			switch {
			case err != nil:
				skip(publishedEditCheck, firstLine(err.Error()))
			case len(hit) == 0:
				checks = append(checks, check{publishedEditCheck,
					fmt.Sprintf("%d edited in place, none published on %s", len(edited), probe.Chain().ID), true, false})
			default:
				checks = append(checks, check{publishedEditCheck, editedWarning(hit), false, true})
			}
		}
	}

	failed := 0
	for _, c := range checks {
		if !c.ok && !c.warn {
			failed++
		}
	}

	var b strings.Builder
	b.WriteString(ciMarker + "\n")
	b.WriteString("### gnopm\n\n")
	b.WriteString(fmt.Sprintf("**%d modules** · %d in tree · %d pinned to history\n\n",
		len(lock.Modules), len(pkgs), len(pinned)))
	b.WriteString("| | check | detail |\n|---|---|---|\n")
	for _, c := range checks {
		mark := "✅"
		switch {
		case c.warn:
			mark = "⚠️"
		case !c.ok:
			mark = "❌"
		}
		b.WriteString(fmt.Sprintf("| %s | %s | %s |\n", mark, c.name, c.detail))
	}
	if base != "" {
		if lines := lockChanges(e.Root, base); len(lines) > 0 {
			b.WriteString("\n**What this changes in `gnomod.lock`**\n\n")
			for _, l := range lines {
				b.WriteString("- " + l + "\n")
			}
		}
	}
	b.WriteString("\n<sub>generated by [gnopm](https://github.com/moul/gnopm)</sub>\n")
	report := b.String()

	fmt.Fprint(e.Out, report)
	// The job summary is where a reader looks first in Actions, and it costs
	// one append.
	if p := os.Getenv("GITHUB_STEP_SUMMARY"); p != "" {
		if f, err := os.OpenFile(p, os.O_APPEND|os.O_WRONLY|os.O_CREATE, 0o644); err == nil {
			fmt.Fprint(f, report)
			f.Close()
		}
	}
	if opts.Comment {
		if err := upsertComment(e, report); err != nil {
			// A comment that cannot be posted must not turn a green run red:
			// the checks are the verdict, the comment is a convenience.
			fmt.Fprintf(e.Errw, "warning: could not post the pull request comment: %v\n", err)
		}
	}
	if failed > 0 {
		return fmt.Errorf("%d check(s) failed, see the report above", failed)
	}
	return nil
}

const ciMarker = "<!-- gnopm-ci-report -->"

// publishedEditCheck is named once: the report, the skips and the tests all
// read the same string, so a reworded check cannot half-rename itself.
const publishedEditCheck = "published versions are not edited in place"

func firstLine(s string) string {
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		return s[:i]
	}
	return s
}

// reproduces re-reads every pinned version out of history and re-hashes it.
func reproduces(root string, pinned []LockEntry) error {
	for _, en := range pinned {
		if _, err := gitResolve(root, en.Source.Commit); err != nil {
			return fmt.Errorf("%s: %w", en.Module, err)
		}
		h, err := hashAtCommit(root, en.Source.Commit, en.Source.Dir)
		if err != nil {
			return fmt.Errorf("%s: %w", en.Module, err)
		}
		if h != en.Hash {
			return fmt.Errorf("%s: history hashes to %s, the lock says %s", en.Module, h, en.Hash)
		}
	}
	return nil
}

// stranded reports pins that a squash merge would discard.
func stranded(root string, pinned []LockEntry, base string) error {
	var bad []string
	for _, en := range pinned {
		if !gitIsAncestor(root, en.Source.Commit, base) {
			bad = append(bad, "`"+en.Module+"`")
		}
	}
	if len(bad) == 0 {
		return nil
	}
	return fmt.Errorf("%s is not on %s yet, so a squash merge would lose it. Bump before editing, or `gnopm tidy`",
		strings.Join(bad, ", "), base)
}

// upsertComment posts the report once and edits it thereafter, so a pull
// request accumulates one comment rather than one per push.
func upsertComment(e *Env, body string) error {
	token := os.Getenv("GITHUB_TOKEN")
	repo := os.Getenv("GITHUB_REPOSITORY")
	if token == "" || repo == "" {
		return fmt.Errorf("GITHUB_TOKEN and GITHUB_REPOSITORY must be set")
	}
	num, err := prNumber()
	if err != nil {
		return err
	}
	id, err := findComment(token, repo, num)
	if err != nil {
		return err
	}
	payload, _ := json.Marshal(map[string]string{"body": body})
	if id != 0 {
		return ghRequest("PATCH", fmt.Sprintf("repos/%s/issues/comments/%d", repo, id), token, payload, nil)
	}
	return ghRequest("POST", fmt.Sprintf("repos/%s/issues/%d/comments", repo, num), token, payload, nil)
}

// prNumber reads the pull request number from the event payload, which is the
// only place it is reliably present: GITHUB_REF is a merge ref and parsing it
// is a guess.
func prNumber() (int, error) {
	p := os.Getenv("GITHUB_EVENT_PATH")
	if p == "" {
		return 0, fmt.Errorf("not running in GitHub Actions (no GITHUB_EVENT_PATH)")
	}
	b, err := os.ReadFile(p)
	if err != nil {
		return 0, err
	}
	var ev struct {
		PullRequest struct{ Number int } `json:"pull_request"`
		Number      int                  `json:"number"`
	}
	if err := json.Unmarshal(b, &ev); err != nil {
		return 0, err
	}
	if ev.PullRequest.Number != 0 {
		return ev.PullRequest.Number, nil
	}
	if ev.Number != 0 {
		return ev.Number, nil
	}
	return 0, fmt.Errorf("this event has no pull request number, so there is nothing to comment on")
}

func findComment(token, repo string, num int) (int64, error) {
	var comments []struct {
		ID   int64  `json:"id"`
		Body string `json:"body"`
	}
	err := ghRequest("GET", fmt.Sprintf("repos/%s/issues/%d/comments?per_page=100", repo, num), token, nil, &comments)
	if err != nil {
		return 0, err
	}
	for _, c := range comments {
		if strings.Contains(c.Body, ciMarker) {
			return c.ID, nil
		}
	}
	return 0, nil
}
