#!/usr/bin/env bash
#
# Build the gnopm demo repository from nothing, and assert at every step that
# gnopm did what it claims.
#
# This is two things at once on purpose:
#
#   * an integration test. It drives the real binary against a real git
#     repository, so it catches the things unit tests cannot: that a rename is
#     recorded as a rename, that a deleted version still materializes, that a
#     bump really is a one-line diff. It needs no network and no GitHub.
#
#   * the demo repository itself. The git history it produces is the
#     documentation: someone can read it commit by commit and watch a
#     versioned-directory repository become a gnomod.lock one, then watch
#     ordinary work happen afterwards.
#
# The repository is rewritten from scratch on every run. Nothing in it is
# precious, which is what lets it always show the current behaviour of the tool
# rather than whatever the behaviour was when someone last remembered to update
# a fixture.
#
# usage:
#   demo.sh <dir>                     build the demo repo at <dir>
#   demo.sh <dir> --push <owner/repo> also force-push it to GitHub
#
# env:
#   GNOPM   path to the gnopm binary (default: build it from source)

set -euo pipefail

target=""
push_to=""
while [ $# -gt 0 ]; do
  case "$1" in
    --push) push_to="${2:?--push needs <owner/repo>}"; shift 2 ;;
    -h|--help) sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    -*) echo "unknown option $1" >&2; exit 2 ;;
    *) target="$1"; shift ;;
  esac
done
[ -n "$target" ] || { echo "usage: demo.sh <dir> [--push <owner/repo>]" >&2; exit 2; }

here="$(cd "$(dirname "$0")" && pwd)"
if [ -z "${GNOPM:-}" ]; then
  GNOPM="$(mktemp -d)/gnopm"
  (cd "$here/.." && go build -o "$GNOPM" .)
fi
gnopm() { "$GNOPM" -C "$repo" "$@"; }

repo="$(mkdir -p "$target" && cd "$target" && pwd)"
rm -rf "${repo:?}/".[!.]* "${repo:?}/"* 2>/dev/null || true
export GNOPM_BIN="$GNOPM" GNOPM_REPO="$repo"

steps=0
step() { steps=$((steps+1)); printf '\n\033[1m== %d. %s\033[0m\n' "$steps" "$1"; }
fail() { printf '\033[31mFAIL: %s\033[0m\n' "$1" >&2; exit 1; }
ok()   { printf '   ok: %s\n' "$1"; }

git_() { git -C "$repo" "$@"; }
# `add -A` is right here and nowhere else: this repository is generated by this
# script and contains nothing anyone else is working on.
commit() { git_ add -A && git_ -c commit.gpgsign=false commit -q -m "$1"; }

write() { mkdir -p "$(dirname "$repo/$1")" && cat > "$repo/$1"; }

# pkg <dir> <modulepath> -- writes a gnomod.toml
pkg() { write "$1/gnomod.toml" <<EOF
module = "$2"
gno = "0.9"
EOF
}

# assert_renames <from-rev> <expected-count>
assert_renames() {
  local n
  n=$(git_ diff --name-status -M "$1" HEAD | grep -c '^R100' || true)
  [ "$n" -eq "$2" ] || fail "expected $2 pure renames, got $n"
  ok "$n files recorded as R100 renames, zero content change"
}

assert_file_lines_changed() {
  local got
  got=$(git_ diff --numstat -- "$1" | awk '{print $1"+"$2}')
  [ "$got" = "$2" ] || fail "$1: expected $2 lines changed, got ${got:-none}"
  ok "$1 changed exactly $2 (added+removed)"
}

assert_grep() { grep -q "$2" <<<"$1" || fail "expected output to contain '$2', got: $1"; ok "output contains '$2'"; }

# ---------------------------------------------------------------------------
step "an empty workspace, in the OLD layout: one directory per version"

git_ init -q -b main
git_ config user.email demo@example.com
git_ config user.name "gnopm demo"
: > "$repo/gnowork.toml"
write .gitignore <<'EOF'
/.gnopm/
EOF
commit "chore: empty gno workspace"

# ---------------------------------------------------------------------------
step "a leaf package, and an external dependency that gnopm does not manage"

pkg p/demo/strs/v0 gno.land/p/demo/strs/v0
write p/demo/strs/v0/strs.gno <<'EOF'
// Package strs is a leaf: it imports nothing.
package strs

// Repeat returns s written n times.
func Repeat(s string, n int) string {
	out := ""
	for i := 0; i < n; i++ {
		out += s
	}
	return out
}
EOF
write p/demo/strs/v0/strs_test.gno <<'EOF'
package strs

func ExampleRepeat() {
	println(Repeat("ab", 3))
	// Output:
	// ababab
}
EOF

# Vendored third-party code. It lives at its own path, is committed, and is
# deliberately outside gnopm's scope: gnopm versions what this repo publishes,
# not what it consumes from elsewhere.
pkg vendor/gno.land/p/nt/tinyavl/v0 gno.land/p/nt/tinyavl/v0
write vendor/gno.land/p/nt/tinyavl/v0/tinyavl.gno <<'EOF'
// Package tinyavl stands in for a real external dependency.
package tinyavl

type Tree struct {
	keys []string
}

func (t *Tree) Set(k string) { t.keys = append(t.keys, k) }
func (t *Tree) Size() int    { return len(t.keys) }
EOF
commit "feat(strs): a leaf package, plus a vendored external dep"

# ---------------------------------------------------------------------------
step "a package that depends on the first one, and on the external one"

pkg p/demo/table/v0 gno.land/p/demo/table/v0
write p/demo/table/v0/table.gno <<'EOF'
// Package table renders rows, and depends on two things: a package this repo
// owns (strs) and a vendored external one (tinyavl).
package table

import (
	"gno.land/p/demo/strs/v0"
	"gno.land/p/nt/tinyavl/v0"
)

type Table struct {
	index tinyavl.Tree
	rows  []string
}

func (t *Table) Add(row string) {
	t.index.Set(row)
	t.rows = append(t.rows, row)
}

// Rule returns a horizontal rule of the given width.
func Rule(width int) string { return strs.Repeat("-", width) }

func (t *Table) Len() int { return t.index.Size() }
EOF
commit "feat(table): depends on strs/v0 and on the vendored tinyavl/v0"

# ---------------------------------------------------------------------------
step "a nested package: the version is the LAST path element, always"

pkg p/demo/math/bignum/v0 gno.land/p/demo/math/bignum/v0
write p/demo/math/bignum/v0/bignum.gno <<'EOF'
// Package bignum sits at p/demo/math/bignum, so its path has a segment after
// "math". The version still goes last: .../math/bignum/v0, never .../math/v0/bignum.
package bignum

func Double(n int) int { return n * 2 }
EOF
commit "feat(math/bignum): a nested package"

# ---------------------------------------------------------------------------
step "the problem this tool exists for: bumping by copying the directory"

cp -r "$repo/p/demo/strs/v0" "$repo/p/demo/strs/v1"
pkg p/demo/strs/v1 gno.land/p/demo/strs/v1
write p/demo/strs/v1/strs.gno <<'EOF'
// Package strs is a leaf: it imports nothing.
package strs

// Repeat returns s written n times.
//
// v1 CHANGED THE SIGNATURE: it now returns an error for a negative count,
// which is exactly the kind of compatibility break a reviewer needs to see.
func Repeat(s string, n int) (string, error) {
	if n < 0 {
		return "", errNegative
	}
	out := ""
	for i := 0; i < n; i++ {
		out += s
	}
	return out, nil
}

var errNegative = errorString("strs: negative count")

type errorString string

func (e errorString) Error() string { return string(e) }
EOF
write p/demo/strs/v1/strs_test.gno <<'EOF'
package strs

func ExampleRepeat() {
	s, _ := Repeat("ab", 3)
	println(s)
	// Output:
	// ababab
}
EOF
commit "feat(strs): v1, Repeat now returns an error (copied directory)"

added=$(git_ diff --numstat HEAD~1 HEAD | awk '{a+=$1; d+=$2} END {print a"+"d}')
ok "the copy-bump diff is $added (added+removed)"
case "$added" in
  *"+0") ok "NOTHING removed: git paired none of it, the compatibility change is invisible" ;;
  *) fail "expected a pure-addition diff from a copy-bump, got $added" ;;
esac

# ---------------------------------------------------------------------------
step "a realm, pinning two different versions of the same package at once"

pkg r/demo/board/v0 gno.land/r/demo/board/v0
write r/demo/board/v0/board.gno <<'EOF'
// Package board is a realm. It deliberately imports strs at BOTH versions,
// through table (which is still on v0) and directly (on v1). Two versions of
// one package coexisting is normal, and any version scheme has to survive it.
package board

import (
	"gno.land/p/demo/strs/v1"
	"gno.land/p/demo/table/v0"
)

var t table.Table

func Add(row string) { t.Add(row) }

func Render(path string) string {
	head, err := strs.Repeat("=", 20)
	if err != nil {
		return "error"
	}
	return head + "\n" + table.Rule(20)
}
EOF
write r/demo/board/v0/board_test.gno <<'EOF'
package board

func ExampleRender() {
	Add("a")
	println(len(Render("")))
	// Output:
	// 41
}
EOF
commit "feat(board): a realm importing strs/v1 directly and strs/v0 via table"

# ---------------------------------------------------------------------------
step "gnopm sees the workspace for the first time"

out=$(gnopm sync 2>&1); echo "$out"
out=$(gnopm status 2>&1); echo "$out"
assert_grep "$out" "5 modules"
assert_grep "$out" "5 in tree"
commit "chore: gnomod.lock, still one directory per version"

# ---------------------------------------------------------------------------
step "the migration: gnopm deversion"

echo "--- the plan ---"
gnopm deversion -n
before_strs_v0=$(cat "$repo/p/demo/strs/v0/strs.gno")
gnopm deversion
commit "refactor: lift every pkg/vN directory up to pkg"

assert_renames HEAD~1 10
out=$(gnopm verify 2>&1); echo "$out"

# strs/v0 no longer has a directory. It must still be byte-identical.
[ ! -d "$repo/p/demo/strs/v0" ] || fail "p/demo/strs/v0 should no longer exist"
got=$(cat "$repo/.gnopm/gno.land/p/demo/strs/v0/strs.gno")
[ "$got" = "$before_strs_v0" ] || fail "strs/v0 was not preserved byte-for-byte"
ok "strs/v0 has no directory, and materializes byte-identically from history"

grep -q 'gno.land/p/demo/strs/v1' "$repo/p/demo/strs/gnomod.toml" \
  || fail "the surviving directory should declare v1"
ok "p/demo/strs/ declares .../strs/v1, and the module line was never rewritten"

out=$(gnopm ls 2>&1); echo "$out"
assert_grep "$out" "history"

# ---------------------------------------------------------------------------
step "ordinary work afterwards: add a package, no version in the directory"

pkg p/demo/set gno.land/p/demo/set/v0
write p/demo/set/set.gno <<'EOF'
// Package set is added AFTER the migration, so it never had a v0 directory.
// The version is in gnomod.toml and nowhere else.
package set

type Set struct{ items []string }

func (s *Set) Add(v string) {
	for _, existing := range s.items {
		if existing == v {
			return
		}
	}
	s.items = append(s.items, v)
}

func (s *Set) Len() int { return len(s.items) }
EOF
gnopm sync
commit "feat(set): a new package, added the new way"

out=$(gnopm ls set 2>&1); echo "$out"
assert_grep "$out" "p/demo/set"

# ---------------------------------------------------------------------------
step "a bump, the new way: one line, and then the real diff"

gnopm bump table
assert_file_lines_changed p/demo/table/gnomod.toml "1+1"
commit "feat(table): bump to v1"

# Now the actual compatibility change, in place, as a normal content diff.
write p/demo/table/table.gno <<'EOF'
// Package table renders rows, and depends on two things: a package this repo
// owns (strs) and a vendored external one (tinyavl).
package table

import (
	"gno.land/p/demo/strs/v1"
	"gno.land/p/nt/tinyavl/v0"
)

type Table struct {
	index tinyavl.Tree
	rows  []string
}

func (t *Table) Add(row string) {
	t.index.Set(row)
	t.rows = append(t.rows, row)
}

// Rule returns a horizontal rule of the given width.
//
// v1 CHANGED: it moved to strs/v1, whose Repeat returns an error, so Rule now
// returns one too. This is the diff a reviewer needs, and here it IS the diff.
func Rule(width int) (string, error) { return strs.Repeat("-", width) }

func (t *Table) Len() int { return t.index.Size() }
EOF
changed=$(git_ diff --numstat -- p/demo/table/table.gno | awk '{print $1"+"$2}')
ok "the v1 content change is a real diff: $changed (added+removed), same file"
case "$changed" in
  *"+0") fail "expected a paired diff, got a pure addition" ;;
esac
commit "feat(table): v1 moves to strs/v1 and returns an error"

# ---------------------------------------------------------------------------
step "the superseded version is still resolvable, and still built"

out=$(gnopm ls -pinned 2>&1); echo "$out"
assert_grep "$out" "gno.land/p/demo/table/v0"
[ -f "$repo/.gnopm/gno.land/p/demo/table/v0/table.gno" ] || fail "table/v0 not materialized"
grep -q 'func Rule(width int) string' "$repo/.gnopm/gno.land/p/demo/table/v0/table.gno" \
  || fail "table/v0 should still carry the OLD signature"
ok "table/v0 keeps its old signature, out of git history, for whatever still imports it"

# board still imports table/v0, and that import still resolves.
grep -q 'gno.land/p/demo/table/v0' "$repo/r/demo/board/board.gno" \
  || fail "board should still pin table/v0"
ok "r/demo/board still pins table/v0 and nothing broke"

# And gnopm can answer that without grep, which is the point of `why`: the
# answer has to include importers that live only under .gnopm/, where a grep
# over the working tree cannot see them.
echo "--- gnopm why gno.land/p/demo/table/v0 ---"
out=$(gnopm why gno.land/p/demo/table/v0 2>&1); echo "$out"
assert_grep "$out" "gno.land/r/demo/board/v0"

# ---------------------------------------------------------------------------
step "skipping versions, and bumping something with an external dependency"

gnopm bump bignum -to 3
grep -q 'gno.land/p/demo/math/bignum/v3' "$repo/p/demo/math/bignum/gnomod.toml" \
  || fail "bignum should be at v3"
ok "bignum jumped v0 to v3 with -to"
commit "feat(math/bignum): bump to v3"

# ---------------------------------------------------------------------------
step "everything the lock knows, and the machine-readable views"

gnopm ls
echo "--- gnopm ls -q (pipeable) ---"
gnopm ls -q
echo "--- gnopm status -json ---"
gnopm status -json
echo "--- gnopm ls -pinned -json ---"
gnopm ls -pinned -json
echo "--- gnopm ls -f (a go-template, as gno list -f does) ---"
gnopm ls -f '{{.Module}}	{{.Source}}'

out=$(gnopm ls -pinned -f '{{.Module}} {{.Commit}}' 2>&1)
assert_grep "$out" "gno.land/p/demo/table/v0"

out=$(gnopm status -json 2>&1)
grep -q '"ok": true' <<<"$out" || fail "status should report ok"
ok "status -json reports ok"

# ---------------------------------------------------------------------------
step "clean, and the claim that makes it safe: sync puts it all back"

before=$(find "$repo/.gnopm" -type f | wc -l | tr -d ' ')
[ "$before" -gt 0 ] || fail "nothing materialized, so this step proves nothing"
echo "--- gnopm clean -n ---"
out=$(gnopm clean -n 2>&1); echo "$out"
assert_grep "$out" "would remove"
[ -d "$repo/.gnopm" ] || fail "clean -n removed the assembly"
echo "--- gnopm clean ---"
gnopm clean
if [ -d "$repo/.gnopm" ]; then fail "clean left the assembly behind"; fi
gnopm sync
after=$(find "$repo/.gnopm" -type f | wc -l | tr -d ' ')
[ "$before" = "$after" ] || fail "sync rebuilt $after files, clean removed $before"
ok "clean drops the assembly and sync rebuilds all $before files from the lock"

# ---------------------------------------------------------------------------
step "the guard: verify fails loudly on a lock that stopped being true"

cp "$repo/gnomod.lock" "$repo/../gnomod.lock.bak" 2>/dev/null || cp "$repo/gnomod.lock" /tmp/gnomod.lock.bak
pkg p/demo/orphan gno.land/p/demo/orphan/v0
write p/demo/orphan/orphan.gno <<'EOF'
package orphan

func Hello() string { return "hi" }
EOF
if gnopm verify >/dev/null 2>&1; then
  fail "verify passed with a package missing from the lock"
fi
out=$(gnopm verify 2>&1 || true)
assert_grep "$out" "gnopm sync"
ok "verify refuses, and says exactly what to run"
gnopm sync
gnopm verify
commit "feat(orphan): a package added without syncing, then synced"

# ---------------------------------------------------------------------------
step "does any of this actually build? ask gno"

# Everything above asserts git and gnopm behaviour. None of it proves the
# generated gno code compiles, and a demo full of code that does not build
# would be worse than no demo. This is the check that keeps it honest.
#
# Skipped when gno is not installed, so the script stays runnable anywhere;
# CI has gno and does run it.
if ! command -v gno >/dev/null 2>&1; then
  echo "   skipped: no gno on PATH"
elif [ -z "${GNOROOT:-}" ]; then
  echo "   skipped: GNOROOT is not set"
else
  gno_dirs=$(cd "$repo" && find p r .gnopm -name gnomod.toml -exec dirname {} \; 2>/dev/null | sort)
  for d in $gno_dirs; do
    (cd "$repo" && gno lint "./$d") || fail "gno lint failed in $d"
  done
  ok "gno lint clean across $(echo "$gno_dirs" | wc -l | tr -d " ") packages"
  for d in $gno_dirs; do
    (cd "$repo" && gno test "./$d" >/dev/null) || fail "gno test failed in $d"
  done
  ok "gno test green, including the versions rebuilt from history under .gnopm/"
fi

# ---------------------------------------------------------------------------
step "the CI a repository needs once it uses gnopm"

# The point of this file is how short it is. Everything it checks lives in the
# gnopm binary, so a repository adopting the convention does not reimplement
# any of it, and does not fall behind when the checks improve.
write .github/workflows/ci.yml <<'YAML'
name: CI
on: [push, pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  gnopm:
    runs-on: ubuntu-latest
    steps:
      # fetch-depth: 0 because gnomod.lock pins versions to commits, and a
      # shallow clone has none of them.
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-go@v5
        with: { go-version: "1.24" }
      - run: go install moul.io/gnopm@latest
      - run: gnopm tool ci --comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
YAML
commit "ci: check the workspace with gnopm"
ok "one short workflow: three checks and a pull request comment"

# ---------------------------------------------------------------------------
step "the README, and the final state"

write README.md <<'EOF'
# gnopm-demo

__BADGES__

**Generated. Rewritten from scratch on every run. Do not send pull requests here.**

This repository is the worked example for
[**gnopm**](https://github.com/moul/gnopm), a
package manager for gno workspaces that keeps a package's version in its
`gnomod.toml` instead of in its directory name.

It is produced by `tools/gnopm/scripts/demo.sh`, which is also gnopm's
integration test: every claim below is asserted by the script that wrote this
file, so if the tool stops behaving this way the script fails rather than
quietly producing a misleading demo.

## Read it as a history, not as a tree

```
git log --reverse --stat
```

The commits tell one story in three acts.

**Act 1, the old layout.** Each version gets its own directory. Watch the
commit that bumps `strs` to v1: it is a pure addition, nothing removed, because
git cannot pair a copied directory. The compatibility change in that commit,
`Repeat` growing an `error` return, is invisible in the diff. That is the
problem.

**Act 2, the migration.** One command, `gnopm deversion`. Every file moves with
`git mv`, so the whole thing is recorded as `R100` renames and reviews as a
rename list. No module line is touched, so no package path and no realm address
changes. `strs/v0`, which had been superseded, stops having a directory and is
pinned in `gnomod.lock` to the commit that still holds it.

**Act 3, ordinary work.** A new package added without a version in its path. A
bump that is one line in `gnomod.toml` followed by the real content diff in the
same file. A version skipped with `-to`. A superseded version still resolving,
still carrying its old signature, for the realm that still imports it.

## What is where

| | |
|---|---|
| `p/demo/strs/` | a leaf package, now at v1; v0 lives only in the lock |
| `p/demo/table/` | depends on `strs` and on a vendored external package |
| `p/demo/math/bignum/` | a nested path: the version is always the LAST element |
| `p/demo/set/` | added after the migration, so it never had a `v0/` directory |
| `r/demo/board/` | a realm pinning two different versions at once |
| `vendor/` | third-party code, committed, deliberately outside gnopm's scope |
| `gnomod.lock` | where every version's source is. Committed: it is source, not a generated artifact |
| `.gnopm/` | superseded versions, rebuilt from history. Gitignored |

## Try it

```
gnopm status          # what resolves, and whether anything is out of date
gnopm ls              # every module and where its source is
gnopm ls -pinned      # just the ones with no directory any more
gnopm verify          # prove every pinned version still reproduces
gnopm bump set        # one line, then edit the files in place
```

## CI

[`.github/workflows/ci.yml`](.github/workflows/ci.yml) is the whole of this
repository's CI. It installs gnopm and runs `gnopm tool ci --comment`, which
checks that the lock describes the tree, that every pinned version reproduces
from history, and that no pin would be discarded by a squash merge, then keeps
one pull request comment up to date with the result.

Nothing in it is specific to this repository: the checks live in the gnopm
binary, so adopting them is installing gnopm rather than copying a workflow.

The badges at the top come from `gnopm badges`.
EOF

# Badges are injected rather than interpolated: an unquoted heredoc would
# evaluate every backtick in the README body, and the body is full of them.
python3 - "$repo/README.md" <<'PYEOF'
import subprocess, sys, os
badges = subprocess.run([os.environ["GNOPM_BIN"], "-C", os.environ["GNOPM_REPO"], "badges"],
                        capture_output=True, text=True).stdout.strip()
p = sys.argv[1]
s = open(p).read().replace("__BADGES__", badges)
open(p, "w").write(s)
PYEOF
commit "docs: what this repository is"

gnopm status
echo
ok "$steps steps, all assertions passed"

if [ -n "$push_to" ]; then
  step "publishing to github.com/$push_to"
  gh repo view "$push_to" >/dev/null 2>&1 || \
    gh repo create "$push_to" --public \
      --description "Generated worked example for gnopm. Rewritten on every run."
  git_ remote remove origin 2>/dev/null || true
  git_ remote add origin "git@github.com:$push_to.git"
  git_ push --force -u origin main
  ok "pushed to https://github.com/$push_to"
fi
